---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: audit-ingest-secret
  namespace: platform
spec:
  encryptedData:
    token: AgAd5+1Z9ZZwE8OCnnpjHL+rJTBOTJSixvOzWNOUZ7pO1oq47amNEKHYIM+2ABWH+3LjrxGHEE5kOqi3gwHn/HbUSJiyyg79uYWX1YmhDjzgy23NytezZSpMsIgNChcuAGiSVMOel4GyAyDZm0z4G7Z4y3e/khIl3+TntGXGMzb7qW3Y2UVZqdhZY/hHiAt+RIi72NcAody9B0H0Gi+9X3sx2NwfEsNs1TAfE0Pt9T9Y/kP1A42zQeXohkFk/+evmfl0ONlXxbn6k37suCGfPpkTg9K+OT8XASSklf4l9QF8j3JwJi1wGcrOanmUACy0zRMP5aalueCkql63sPSLRDK4/SmqPSMg4sU5ATYFN4g0gU5V15LvuMjd/7UPwyVY/2pmLye1YbsoQqX7jGx2ruDOtD4C9+RaT2+kB/GD2nJyq4ju6+TZMO69uijfDOh8HzBrsXE7hCh5qQZwpBMEy0Lld2Hro725Qo5W+tSraC8GoBXUsQragz0cpSguqqlunxlODepBfoSbUtdGH7OfL13bwoumiSaz3Abb/ZXRagzETeJ0z83d5Whkw/vtVd0aSmNMZhIYf+eThGIrvCQ6/R1bBa+NIwuy5386CZ7unjdThfpZe71y0wQXdM7MmsLCUSjoWxkFhCZNQtG/MLpOWnSbrdIJsmvUZ1uf/KJ5xSKtpOnd/TTnwI6vHRv1zMoB/mYHEZQxo/sIaBxCtwR0vQLzQ985zKBIJOPDtGn2t/mJ7yWRo8xnN+4wPXGxkJRnUFakkpJH6RriSWhOSMjXC00/
  template:
    metadata:
      name: audit-ingest-secret
      namespace: platform
