---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: audit-ingest-secret
  namespace: platform
spec:
  encryptedData:
    token: AgAmY/lSO0DdMZKsxcuihITHL+MOf8FTcfvBC8jr8IJccBBEdhdsDmKTtl/1TkBYDmbmBRttAb7dHACKSO7GQjdYpb2SgTCstLvmTqlomt0QfZcjcPajUpcUeyhAvJkNITmQVly2mqMmZs65RKrNLFtuZxuXZyRh9mG7jtqAD52LLF0urSCtd4OfH/aoYgYH6kajCsIsDkR8tAnN+LE3ZLdjOlxo5ve5eH+0iPAM5EW830aFlBssk6DMFfwHIUJ/wdXI5ptzljfIQOxjCRVruWRpsJieiLQ4PRMOFB3VctYfGyUg9fcef2b0tmDW6yuvhQrilLpM2WmaqQIFwhLC11gCoFM+0yLn1A3zv5lcRcAu/YuOf5Ehjmb58iJq+QJgS6J9SJkwcwb1CiexS+qBgYfQhW0ebrnIBbq1SU2jaigGfd1Xp/YmaT5hJmuimf10LAHcpUBQe5/8WxZLjzkl3xAmz6TKidyM7pPSwBSbMWqJgFZFQJ7CvozUFxDDGE/Q+5fATIZydW/NqLNhozXcU3QxmeM1li/AVsX0VAHv4N5vbeQ1sNL1p4rM/pPAsPFKc7pz7dCEa1fThh6486cfS97ZBScgRZl82WiHNv6OMEZW1e1WQke56LWr9VdhwWUl01coywNqaNdqiyNJZQI/8r4ayENyP5IF08207G/SOu99xSKLHoKo6NEZSv8sqVNK/dQdww57bS7+8DyC1d6KLvxObUX2QWsjibPc7sCAMNc3p1jM0VcnL07J
  template:
    metadata:
      creationTimestamp: null
      name: audit-ingest-secret
      namespace: platform
